config/routes.rb
Rails.application.routes.draw do
  resources :trackings
  root to: "trackings#consulta"

  controller :trackings do
    :consulta
    :error
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tracking.rb
class Tracking < ApplicationRecord
  validates :guia, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  protect_from_forgery
  before_action :set_tracking, only: %i[ show edit update destroy ]
  before_action :set_fedex, only: [:consulta, :index]

  def consulta
  end

  # GET /trackings or /trackings.json
  def index
    @trackings = Tracking.all

    if params[:buscar_guia].present?
      tracking_this = Tracking.find_by guia: params[:buscar_guia] #busca el numero de guia dentro de TRACKING
      results = @fedex.track(tracking_number: params[:buscar_guia]) #busca el paquete en la api de fedex

      if results.last.tracking_number.present? #verifica si hay un ultimo seguimiento
        tracking_info = results.last
        tracking = Tracking.new
        tracking.nombre = tracking_info.signature_name
        tracking.estado = tracking_info.status
        tracking.desde = results.second.events.first.city + ", " + results.second.events.first.state + " " + results.second.events.first.country
        tracking.hasta = results.last.events.first.city + ", " + results.last.events.first.state + " " + results.last.events.first.country
        tracking.description = results.last.events.first.description
        if tracking_this.present? #con esto me aseguro de que grabe en la base de datos local la ultima actualizacion del seguimiento
          tracking.save
        else
          tracking.guia = tracking_info.tracking_number #si la guia no existe en la base de datos local, la guarda
          tracking.save
        end
      end
    end

    @numero = 0

  rescue
    render 'error'
  end

  def error
  end

  # GET /trackings/1 or /trackings/1.json
  def show
  end

  # GET /trackings/new
  def new
    @tracking = Tracking.new
  end

  # GET /trackings/1/edit
  def edit
  end

  # POST /trackings or /trackings.json
  def create
    @tracking = Tracking.new(tracking_params)

    respond_to do |format|
      if @tracking.save
        format.html { redirect_to @tracking, notice: "Tracking was successfully created." }
        format.json { render :show, status: :created, location: @tracking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackings/1 or /trackings/1.json
  def update
    respond_to do |format|
      if @tracking.update(tracking_params)
        format.html { redirect_to @tracking, notice: "Tracking was successfully updated." }
        format.json { render :show, status: :ok, location: @tracking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackings/1 or /trackings/1.json
  def destroy
    @tracking.destroy
    respond_to do |format|
      format.html { redirect_to trackings_url, notice: "Tracking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tracking
    @tracking = Tracking.find(params[:id])
  end

  def set_fedex
    @fedex = Fedex::Shipment.new(
        key: "#{ENV["fedex_test_key"]}", #reemplazar con la key que corresponda
        password: "#{ENV["fedex_test_password"]}", #reemplazar con el password que corresponda
        account_number: "#{ENV["fedex_test_account"]}", #reemplazar con la cuenta que corresponda
        meter: '100495015',
        mode: "#{ENV["fedex_test_mode"]}"
    )
  end

  # Only allow a list of trusted parameters through.
  def tracking_params
    params.require(:tracking).permit(:nombre, :guia, :estado, :desde, :hasta, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackingFedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trackings/_form.html.erb
<%= form_with(model: tracking) do |form| %>
  <% if tracking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracking.errors.count, "error") %> prohibited this tracking from being saved:</h2>

      <ul>
        <% tracking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :guia %>
    <%= form.text_field :guia %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trackings/consulta.html.erb
<div class="consulta">
  <div class="container d-flex justify-content-center">
    <%= form_tag trackings_path, method: :get do %>
      <div class="form-group row">
        <div class="col-form-label-sm">
          <p>Ingrese código de guía</p>
          <%= text_field_tag :buscar_guia, params[:buscar_guia], class:'form-control', placeholder: 'n° de guia'%>
        </div>
        <div class="text-center mt-5">
          <%= submit_tag 'Buscar', class: 'btn btn-primary btn-md' %>
        </div>
        <!--<div class="col-2">
        <%#= link_to 'Todos', listar_pacientes_path, class: 'btn btn-primary' %>
      </div>-->
      </div>
    <% end %>
  </div>
</div>

app/views/trackings/edit.html.erb
<h1>Editing Tracking</h1>

<%= render 'form', tracking: @tracking %>

<%= link_to 'Show', @tracking %> |
<%= link_to 'Back', trackings_path %>

app/views/trackings/error.html.erb
<div class="error">
  <div class="container d-flex justify-content-center flex-column">
    <div class="text-center">
      <h4>N° de guía no encontrado</h4>
    </div>
    <br>
    <div class="text-center mt-5">
      <%= link_to 'Nueva consulta', root_path, class: 'btn btn-primary btn-md text-white' %>
    </div>
  </div>
</div>

app/views/trackings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="seguimientos">
  <div class="container-md d-flex justify-content-center flex-column">
    <div class="container2">
      <h2 class="text-center mb-5">Seguimientos</h2>

      <div class="accordion accordion-flush" id="accordionFlushExample">
        <% @trackings.each do |tracking| %>
          <% @numero += 1 %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-heading<%= @numero %>">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= @numero %>" aria-expanded="false" aria-controls="flush-collapse<%= @numero %>">
                <p class="text-black">
                  <%= tracking.guia %>
                  <%= link_to 'Eliminar', tracking, method: :delete, data: {confirm: 'Seguro?'} %>
                </p>
              </button>
            </h2>
            <div id="flush-collapse<%= @numero %>" class="accordion-collapse collapse" aria-labelledby="flush-heading<%= @numero %>" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body">
                Nombre: <code><%= tracking.nombre %></code> <br>
                Desde: <code><%= tracking.desde %></code> <br>
                Hasta: <code><%= tracking.hasta %></code> <br>
                Descripción: <code><%= tracking.description %></code> <br>
                Estado: <code><%= tracking.estado %></code> <br>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <br>

      <div class="text-center mt-5">
        <%= link_to 'Nueva consulta', root_path, class: 'btn btn-primary btn-md text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/trackings/new.html.erb
<h1>New Tracking</h1>

<%= render 'form', tracking: @tracking %>

<%= link_to 'Back', trackings_path %>

app/views/trackings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tracking.nombre %>
</p>

<p>
  <strong>Guia:</strong>
  <%= @tracking.guia %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @tracking.estado %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tracking.descripcion %>
</p>

<%= link_to 'Edit', edit_tracking_path(@tracking) %> |
<%= link_to 'Back', trackings_path %>